INFO     2020-10-06 18:46:49.267 request id: app - uvicorn.main:serve - Started server process [43737]
INFO     2020-10-06 18:46:49.268 request id: app - uvicorn.lifespan.on:startup - Waiting for application startup.
INFO     2020-10-06 18:46:49.269 request id: app - uvicorn.lifespan.on:startup - Application startup complete.
INFO     2020-10-06 18:46:49.270 request id: app - uvicorn.main:startup - Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
ERROR    2020-10-06 18:47:37.427 request id: app - uvicorn.protocols.http.h11_impl:run_asgi - Exception in ASGI application

Traceback (most recent call last):

  File "main.py", line 128, in <module>
    uvicorn.run(app, port=8000)
    │       │   └ <fastapi.applications.FastAPI object at 0x10835d1f0>
    │       └ <function run at 0x10958db80>
    └ <module 'uvicorn' from '/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/uvicorn/main.py", line 379, in run
    server.run()
    │      └ <function Server.run at 0x1095e1f70>
    └ <uvicorn.main.Server object at 0x1097860a0>
  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/uvicorn/main.py", line 407, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x1095ea040>
    │    │                  └ <uvicorn.main.Server object at 0x1097860a0>
    │    └ <function BaseEventLoop.run_until_complete at 0x1088e20d0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x1088e2040>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x1088e3b80>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x108875940>
    └ <Handle <TaskStepMethWrapper object at 0x1097f5b80>()>
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x1097f5b80>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x1097f5b80>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x1097f5b80>()>
> File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
                   │   │    │      │    │        │    └ <function RequestResponseCycle.send at 0x1097f31f0>
                   │   │    │      │    │        └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1097f5490>
                   │   │    │      │    └ <function RequestResponseCycle.receive at 0x1097f3280>
                   │   │    │      └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1097f5490>
                   │   │    └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
                   │   └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1097f5490>
                   └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x109786220>
  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
                 │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1097f5490>>
                 │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1097f5490>>
                 │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
                 │    └ <fastapi.applications.FastAPI object at 0x10835d1f0>
                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x109786220>
  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1097f5490>>
                           │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1097f5490>>
                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1097f5490>>
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1097f5490>>
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x1096f7280>
          └ <fastapi.applications.FastAPI object at 0x10835d1f0>
  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x1097f38b0>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1097f5490>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <starlette.exceptions.ExceptionMiddleware object at 0x1096f7040>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x1096f7280>
  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x1097f3940>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1097f5490>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <fastapi.routing.APIRouter object at 0x10834e2e0>
          └ <starlette.exceptions.ExceptionMiddleware object at 0x1096f7040>
  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x1097f3940>
          │     │      │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1097f5490>>
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │     └ <function Route.handle at 0x1094161f0>
          └ <fastapi.routing.APIRoute object at 0x109786910>
  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x1097f3940>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1097f5490>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <function request_response.<locals>.app at 0x10977faf0>
          └ <fastapi.routing.APIRoute object at 0x109786910>
  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
                     │    └ <starlette.requests.Request object at 0x1097f5a90>
                     └ <function get_request_handler.<locals>.app at 0x10977fa60>
  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/fastapi/routing.py", line 182, in app
    raw_response = await run_endpoint_function(
                         └ <function run_endpoint_function at 0x109405310>
  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/fastapi/routing.py", line 133, in run_endpoint_function
    return await dependant.call(**values)
                 │         │      └ {}
                 │         └ <function client_init at 0x10977f9d0>
                 └ <fastapi.dependencies.models.Dependant object at 0x109786a90>

  File "main.py", line 34, in client_init
    request.app.logger.info("Here Is Your Error Log")

NameError: name 'request' is not defined
INFO     2020-10-06 18:48:39.336 request id: app - uvicorn.main:shutdown - Shutting down
INFO     2020-10-06 18:48:39.439 request id: app - uvicorn.lifespan.on:shutdown - Waiting for application shutdown.
INFO     2020-10-06 18:48:39.441 request id: app - uvicorn.lifespan.on:shutdown - Application shutdown complete.
INFO     2020-10-06 18:48:39.441 request id: app - uvicorn.main:serve - Finished server process [43737]
INFO     2020-10-06 18:48:40.771 request id: app - uvicorn.main:serve - Started server process [43835]
INFO     2020-10-06 18:48:40.771 request id: app - uvicorn.lifespan.on:startup - Waiting for application startup.
INFO     2020-10-06 18:48:40.773 request id: app - uvicorn.lifespan.on:startup - Application startup complete.
INFO     2020-10-06 18:48:40.774 request id: app - uvicorn.main:startup - Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO     2020-10-06 18:49:00.750 request id: None - __main__:client_init - Here Is Your Error Log
ERROR    2020-10-06 18:49:01.797 request id: app - uvicorn.protocols.http.h11_impl:run_asgi - Exception in ASGI application

Traceback (most recent call last):

  File "main.py", line 128, in <module>
    uvicorn.run(app, port=8000)
    │       │   └ <fastapi.applications.FastAPI object at 0x10646b1f0>
    │       └ <function run at 0x10769bb80>
    └ <module 'uvicorn' from '/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/uvicorn/main.py", line 379, in run
    server.run()
    │      └ <function Server.run at 0x1076f0f70>
    └ <uvicorn.main.Server object at 0x1078570a0>
  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/uvicorn/main.py", line 407, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x1076f8040>
    │    │                  └ <uvicorn.main.Server object at 0x1078570a0>
    │    └ <function BaseEventLoop.run_until_complete at 0x1069f00d0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x1069f0040>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x1069f1b80>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x106983940>
    └ <Handle <TaskStepMethWrapper object at 0x1078edc40>()>
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x1078edc40>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x1078edc40>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x1078edc40>()>
> File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
                   │   │    │      │    │        │    └ <function RequestResponseCycle.send at 0x1078ce1f0>
                   │   │    │      │    │        └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1078f3d60>
                   │   │    │      │    └ <function RequestResponseCycle.receive at 0x1078ce280>
                   │   │    │      └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1078f3d60>
                   │   │    └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
                   │   └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1078f3d60>
                   └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x107857220>
  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
                 │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1078f3d60>>
                 │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1078f3d60>>
                 │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
                 │    └ <fastapi.applications.FastAPI object at 0x10646b1f0>
                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x107857220>
  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1078f3d60>>
                           │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1078f3d60>>
                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1078f3d60>>
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1078f3d60>>
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x107805280>
          └ <fastapi.applications.FastAPI object at 0x10646b1f0>
  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x1078ce8b0>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1078f3d60>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <starlette.exceptions.ExceptionMiddleware object at 0x107805040>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x107805280>
  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x1078ce940>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1078f3d60>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <fastapi.routing.APIRouter object at 0x10645c2e0>
          └ <starlette.exceptions.ExceptionMiddleware object at 0x107805040>
  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x1078ce940>
          │     │      │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1078f3d60>>
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │     └ <function Route.handle at 0x1075241f0>
          └ <fastapi.routing.APIRoute object at 0x107857940>
  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x1078ce940>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1078f3d60>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <function request_response.<locals>.app at 0x10784baf0>
          └ <fastapi.routing.APIRoute object at 0x107857940>
  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
                     │    └ <starlette.requests.Request object at 0x1078f3190>
                     └ <function get_request_handler.<locals>.app at 0x10784ba60>
  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/fastapi/routing.py", line 182, in app
    raw_response = await run_endpoint_function(
                         └ <function run_endpoint_function at 0x107514310>
  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/fastapi/routing.py", line 133, in run_endpoint_function
    return await dependant.call(**values)
                 │         │      └ {}
                 │         └ <function client_init at 0x10784b9d0>
                 └ <fastapi.dependencies.models.Dependant object at 0x107857a30>

  File "main.py", line 35, in client_init
    dump_data()
    └ <function dump_data at 0x10776fb80>

  File "/Users/kamil/Desktop/plenilune/name_server/dataworker.py", line 12, in dump_data
    set_data({
    └ <function set_data at 0x10777a040>

  File "/Users/kamil/Desktop/plenilune/name_server/dataworker.py", line 44, in set_data
    conn.set("data", json.dumps(data))
    │    │           │    │     └ {'block_size': 1024, 'replication': 2, 'fsimage': {'.': {'dirs': [], 'files': {}}}, 'storage_servers': [{'id': 1, 'hostname':...
    │    │           │    └ <function dumps at 0x106a43c10>
    │    │           └ <module 'json' from '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__....
    │    └ <function Redis.set at 0x1077f6820>
    └ Redis<ConnectionPool<Connection<host=redis,port=6379,db=0>>>

  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/redis/client.py", line 1801, in set
    return self.execute_command('SET', *pieces)
           │    │                       └ ['data', '{"block_size": 1024, "replication": 2, "fsimage": {".": {"dirs": [], "files": {}}}, "storage_servers": [{"id": 1, "...
           │    └ <function Redis.execute_command at 0x1077f3280>
           └ Redis<ConnectionPool<Connection<host=redis,port=6379,db=0>>>
  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
           │    │             │    │              │               └ {}
           │    │             │    │              └ 'SET'
           │    │             │    └ <function ConnectionPool.get_connection at 0x1077ec0d0>
           │    │             └ ConnectionPool<Connection<host=redis,port=6379,db=0>>
           │    └ None
           └ Redis<ConnectionPool<Connection<host=redis,port=6379,db=0>>>
  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
    │          └ <function Connection.connect at 0x1077eb310>
    └ Connection<host=redis,port=6379,db=0>
  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
          │               │    └ <function Connection._error_message at 0x1077eb430>
          │               └ Connection<host=redis,port=6379,db=0>
          └ <class 'redis.exceptions.ConnectionError'>

redis.exceptions.ConnectionError: Error 8 connecting to redis:6379. nodename nor servname provided, or not known.
INFO     2020-10-06 18:49:39.259 request id: app - uvicorn.main:shutdown - Shutting down
INFO     2020-10-06 18:49:39.363 request id: app - uvicorn.lifespan.on:shutdown - Waiting for application shutdown.
INFO     2020-10-06 18:49:39.365 request id: app - uvicorn.lifespan.on:shutdown - Application shutdown complete.
INFO     2020-10-06 18:49:39.366 request id: app - uvicorn.main:serve - Finished server process [43835]
INFO     2020-10-06 18:50:32.755 request id: app - uvicorn.main:serve - Started server process [43915]
INFO     2020-10-06 18:50:32.755 request id: app - uvicorn.lifespan.on:startup - Waiting for application startup.
INFO     2020-10-06 18:50:32.756 request id: app - uvicorn.lifespan.on:startup - Application startup complete.
INFO     2020-10-06 18:50:32.758 request id: app - uvicorn.main:startup - Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
ERROR    2020-10-06 18:51:02.054 request id: app - uvicorn.protocols.http.h11_impl:run_asgi - Exception in ASGI application

Traceback (most recent call last):

  File "main.py", line 127, in <module>
    uvicorn.run(app, port=8000)
    │       │   └ <fastapi.applications.FastAPI object at 0x10d135250>
    │       └ <function run at 0x10e365b80>
    └ <module 'uvicorn' from '/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/uvicorn/__init__.py'>

  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/uvicorn/main.py", line 379, in run
    server.run()
    │      └ <function Server.run at 0x10e3b9f70>
    └ <uvicorn.main.Server object at 0x10e2587c0>
  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/uvicorn/main.py", line 407, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x10e3c2040>
    │    │                  └ <uvicorn.main.Server object at 0x10e2587c0>
    │    └ <function BaseEventLoop.run_until_complete at 0x10d6ba0d0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x10d6ba040>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x10d6bbb80>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x10d64d940>
    └ <Handle <TaskStepMethWrapper object at 0x10e5aa580>()>
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x10e5aa580>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x10e5aa580>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x10e5aa580>()>
> File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
                   │   │    │      │    │        │    └ <function RequestResponseCycle.send at 0x10e5a91f0>
                   │   │    │      │    │        └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10e5aa1f0>
                   │   │    │      │    └ <function RequestResponseCycle.receive at 0x10e5a9280>
                   │   │    │      └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10e5aa1f0>
                   │   │    └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
                   │   └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10e5aa1f0>
                   └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x10e51f1f0>
  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
                 │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10e5aa1f0>>
                 │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10e5aa1f0>>
                 │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
                 │    └ <fastapi.applications.FastAPI object at 0x10d135250>
                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x10e51f1f0>
  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10e5aa1f0>>
                           │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10e5aa1f0>>
                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10e5aa1f0>>
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10e5aa1f0>>
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x10e4cf2e0>
          └ <fastapi.applications.FastAPI object at 0x10d135250>
  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x10e5a98b0>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10e5aa1f0>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <starlette.exceptions.ExceptionMiddleware object at 0x10e4cf040>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x10e4cf2e0>
  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x10e5a9940>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10e5aa1f0>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <fastapi.routing.APIRouter object at 0x10d122370>
          └ <starlette.exceptions.ExceptionMiddleware object at 0x10e4cf040>
  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x10e5a9940>
          │     │      │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10e5aa1f0>>
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │     └ <function Route.handle at 0x10e1ee1f0>
          └ <fastapi.routing.APIRoute object at 0x10e51f910>
  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x10e5a9940>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10e5aa1f0>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <function request_response.<locals>.app at 0x10e514af0>
          └ <fastapi.routing.APIRoute object at 0x10e51f910>
  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
                     │    └ <starlette.requests.Request object at 0x10e5aa460>
                     └ <function get_request_handler.<locals>.app at 0x10e514a60>
  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/fastapi/routing.py", line 182, in app
    raw_response = await run_endpoint_function(
                         └ <function run_endpoint_function at 0x10e1de310>
  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/fastapi/routing.py", line 133, in run_endpoint_function
    return await dependant.call(**values)
                 │         │      └ {}
                 │         └ <function client_init at 0x10e5149d0>
                 └ <fastapi.dependencies.models.Dependant object at 0x10e51fa00>

  File "main.py", line 34, in client_init
    # dump_data()

  File "/Users/kamil/Desktop/plenilune/name_server/dataworker.py", line 12, in dump_data
    set_data({
    └ <function set_data at 0x10e444040>

  File "/Users/kamil/Desktop/plenilune/name_server/dataworker.py", line 44, in set_data
    conn.set("data", json.dumps(data))
    │    │           │    │     └ {'block_size': 1024, 'replication': 2, 'fsimage': {'.': {'dirs': [], 'files': {}}}, 'storage_servers': [{'id': 1, 'hostname':...
    │    │           │    └ <function dumps at 0x10d70ec10>
    │    │           └ <module 'json' from '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__....
    │    └ <function Redis.set at 0x10e4c0820>
    └ Redis<ConnectionPool<Connection<host=redis,port=6379,db=0>>>

  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/redis/client.py", line 1801, in set
    return self.execute_command('SET', *pieces)
           │    │                       └ ['data', '{"block_size": 1024, "replication": 2, "fsimage": {".": {"dirs": [], "files": {}}}, "storage_servers": [{"id": 1, "...
           │    └ <function Redis.execute_command at 0x10e4bd280>
           └ Redis<ConnectionPool<Connection<host=redis,port=6379,db=0>>>
  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
           │    │             │    │              │               └ {}
           │    │             │    │              └ 'SET'
           │    │             │    └ <function ConnectionPool.get_connection at 0x10e4b60d0>
           │    │             └ ConnectionPool<Connection<host=redis,port=6379,db=0>>
           │    └ None
           └ Redis<ConnectionPool<Connection<host=redis,port=6379,db=0>>>
  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
    │          └ <function Connection.connect at 0x10e4b4310>
    └ Connection<host=redis,port=6379,db=0>
  File "/Users/kamil/Desktop/plenilune/name_server/venv/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
          │               │    └ <function Connection._error_message at 0x10e4b4430>
          │               └ Connection<host=redis,port=6379,db=0>
          └ <class 'redis.exceptions.ConnectionError'>

redis.exceptions.ConnectionError: Error 8 connecting to redis:6379. nodename nor servname provided, or not known.
INFO     2020-10-06 18:51:06.802 request id: app - uvicorn.main:shutdown - Shutting down
INFO     2020-10-06 18:51:06.906 request id: app - uvicorn.lifespan.on:shutdown - Waiting for application shutdown.
INFO     2020-10-06 18:51:06.908 request id: app - uvicorn.lifespan.on:shutdown - Application shutdown complete.
INFO     2020-10-06 18:51:06.909 request id: app - uvicorn.main:serve - Finished server process [43915]
INFO     2020-10-06 18:51:08.041 request id: app - uvicorn.main:serve - Started server process [43964]
INFO     2020-10-06 18:51:08.042 request id: app - uvicorn.lifespan.on:startup - Waiting for application startup.
INFO     2020-10-06 18:51:08.043 request id: app - uvicorn.lifespan.on:startup - Application startup complete.
INFO     2020-10-06 18:51:08.044 request id: app - uvicorn.main:startup - Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO     2020-10-06 18:51:38.640 request id: app - uvicorn.main:shutdown - Shutting down
INFO     2020-10-06 18:51:38.746 request id: app - uvicorn.lifespan.on:shutdown - Waiting for application shutdown.
INFO     2020-10-06 18:51:38.749 request id: app - uvicorn.lifespan.on:shutdown - Application shutdown complete.
INFO     2020-10-06 18:51:38.750 request id: app - uvicorn.main:serve - Finished server process [43964]
INFO     2020-10-06 18:51:39.797 request id: app - uvicorn.main:serve - Started server process [44011]
INFO     2020-10-06 18:51:39.798 request id: app - uvicorn.lifespan.on:startup - Waiting for application startup.
INFO     2020-10-06 18:51:39.799 request id: app - uvicorn.lifespan.on:startup - Application startup complete.
INFO     2020-10-06 18:51:39.800 request id: app - uvicorn.main:startup - Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO     2020-10-06 18:51:42.342 request id: None - __main__:client_init - Here Is Your Error Log
INFO     2020-10-06 18:51:55.730 request id: None - __main__:client_init - Here Is Your Error Log
INFO     2020-10-06 18:51:59.047 request id: app - uvicorn.main:shutdown - Shutting down
INFO     2020-10-06 18:51:59.154 request id: app - uvicorn.lifespan.on:shutdown - Waiting for application shutdown.
INFO     2020-10-06 18:51:59.155 request id: app - uvicorn.lifespan.on:shutdown - Application shutdown complete.
INFO     2020-10-06 18:51:59.156 request id: app - uvicorn.main:serve - Finished server process [44011]
INFO     2020-10-06 18:52:00.714 request id: app - uvicorn.main:serve - Started server process [44048]
INFO     2020-10-06 18:52:00.715 request id: app - uvicorn.lifespan.on:startup - Waiting for application startup.
INFO     2020-10-06 18:52:00.716 request id: app - uvicorn.lifespan.on:startup - Application startup complete.
INFO     2020-10-06 18:52:00.717 request id: app - uvicorn.main:startup - Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO     2020-10-06 18:52:29.883 request id: app - uvicorn.main:shutdown - Shutting down
INFO     2020-10-06 18:52:29.990 request id: app - uvicorn.lifespan.on:shutdown - Waiting for application shutdown.
INFO     2020-10-06 18:52:29.992 request id: app - uvicorn.lifespan.on:shutdown - Application shutdown complete.
INFO     2020-10-06 18:52:29.993 request id: app - uvicorn.main:serve - Finished server process [44048]
INFO     2020-10-06 18:52:31.059 request id: app - uvicorn.main:serve - Started server process [44102]
INFO     2020-10-06 18:52:31.059 request id: app - uvicorn.lifespan.on:startup - Waiting for application startup.
INFO     2020-10-06 18:52:31.060 request id: app - uvicorn.lifespan.on:startup - Application startup complete.
INFO     2020-10-06 18:52:31.061 request id: app - uvicorn.main:startup - Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
WARNING  2020-10-06 18:52:33.432 request id: None - __main__:client_init - Here Is Your Error Log
INFO     2020-10-06 18:53:05.533 request id: app - uvicorn.main:shutdown - Shutting down
INFO     2020-10-06 18:53:05.638 request id: app - uvicorn.lifespan.on:shutdown - Waiting for application shutdown.
INFO     2020-10-06 18:53:05.641 request id: app - uvicorn.lifespan.on:shutdown - Application shutdown complete.
INFO     2020-10-06 18:53:05.642 request id: app - uvicorn.main:serve - Finished server process [44102]
DEBUG    2020-10-06 18:53:06.530 request id: app - asyncio.selector_events:__init__ - Using selector: KqueueSelector
INFO     2020-10-06 18:53:06.543 request id: app - uvicorn.main:serve - Started server process [44179]
INFO     2020-10-06 18:53:06.544 request id: app - uvicorn.lifespan.on:startup - Waiting for application startup.
INFO     2020-10-06 18:53:06.545 request id: app - uvicorn.lifespan.on:startup - Application startup complete.
INFO     2020-10-06 18:53:06.546 request id: app - uvicorn.main:startup - Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
DEBUG    2020-10-06 18:53:07.979 request id: None - __main__:client_init - Here Is Your Error Log
DEBUG    2020-10-06 18:53:16.065 request id: None - __main__:client_init - Here Is Your Error Log
INFO     2020-10-06 18:53:28.273 request id: app - uvicorn.main:shutdown - Shutting down
INFO     2020-10-06 18:53:28.378 request id: app - uvicorn.lifespan.on:shutdown - Waiting for application shutdown.
INFO     2020-10-06 18:53:28.380 request id: app - uvicorn.lifespan.on:shutdown - Application shutdown complete.
INFO     2020-10-06 18:53:28.381 request id: app - uvicorn.main:serve - Finished server process [44179]
DEBUG    2020-10-06 18:53:29.373 request id: app - asyncio.selector_events:__init__ - Using selector: KqueueSelector
INFO     2020-10-06 18:53:29.391 request id: app - uvicorn.main:serve - Started server process [44215]
INFO     2020-10-06 18:53:29.391 request id: app - uvicorn.lifespan.on:startup - Waiting for application startup.
INFO     2020-10-06 18:53:29.393 request id: app - uvicorn.lifespan.on:startup - Application startup complete.
INFO     2020-10-06 18:53:29.394 request id: app - uvicorn.main:startup - Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO     2020-10-06 18:53:30.831 request id: None - __main__:client_init - Here Is Your Error Log
INFO     2020-10-06 18:53:34.100 request id: None - __main__:client_init - Here Is Your Error Log
INFO     2020-10-06 18:53:44.624 request id: app - uvicorn.main:shutdown - Shutting down
INFO     2020-10-06 18:53:44.730 request id: app - uvicorn.lifespan.on:shutdown - Waiting for application shutdown.
INFO     2020-10-06 18:53:44.733 request id: app - uvicorn.lifespan.on:shutdown - Application shutdown complete.
INFO     2020-10-06 18:53:44.734 request id: app - uvicorn.main:serve - Finished server process [44215]
DEBUG    2020-10-06 18:53:45.701 request id: app - asyncio.selector_events:__init__ - Using selector: KqueueSelector
INFO     2020-10-06 18:53:45.717 request id: app - uvicorn.main:serve - Started server process [44251]
INFO     2020-10-06 18:53:45.718 request id: app - uvicorn.lifespan.on:startup - Waiting for application startup.
INFO     2020-10-06 18:53:45.719 request id: app - uvicorn.lifespan.on:startup - Application startup complete.
INFO     2020-10-06 18:53:45.720 request id: app - uvicorn.main:startup - Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
DEBUG    2020-10-06 18:53:47.166 request id: None - __main__:client_init - Here Is Your Error Log
